server:
  port: 8080

spring:  application:    name: Project2-Backend
  # Database Credentials
  datasource:    username: ${P2U}
    password: ${P2P}
    url: jdbc:postgresql://database-1.ca5zmwzvmpcx.us-east-2.rds.amazonaws.com:5432/postgres
  # hbm2ddl 
  jackson:    serialization:      fail-on-empty-beans: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect  
    hibernate:
      ddl-auto: update
      
      