server:
  port: 8082

spring:  application:    name: Project2-Backend
  # Database Credentials
  datasource:    username: ${Pirate_Login}
    password: ${Pirate_PW}
    url: jdbc:postgresql://localhost:5432/postgres
  # hbm2ddl 
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect  
    hibernate:
      ddl-auto: update
      
      